import { useEffect, useState } from "react";
import { View, Text, Pressable, StyleSheet, ScrollView } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Image } from "expo-image";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";

import { theme } from "@/src/lib/theme";
import { getPrinter, setPrinter, SavedPrinter, KITCHEN_NAME } from "@/src/lib/storage";
import { disconnectPrinter, isNativePrinterAvailable } from "@/src/lib/printer";
import { tap } from "@/src/lib/haptics";

export default function SettingsScreen() {
  const router = useRouter();
  const [printer, setPrinterState] = useState<SavedPrinter | null>(null);

  useEffect(() => {
    (async () => {
      const p = await getPrinter();
      setPrinterState(p);
    })();
  }, []);

  const onDisconnect = async () => {
    tap();
    await disconnectPrinter();
    await setPrinter(null);
    setPrinterState(null);
  };

  const onChangePrinter = () => {
    tap();
    router.push("/printer-setup");
  };

  return (
    <SafeAreaView style={styles.safe} edges={["top", "bottom"]}>
      <View style={styles.header}>
        <Pressable
          testID="settings-back"
          onPress={() => router.back()}
          hitSlop={10}
          style={styles.iconBtn}
        >
          <Ionicons name="chevron-back" size={22} color={theme.color.onSurface} />
        </Pressable>
        <Text style={styles.headerTitle}>Settings</Text>
        <View style={{ width: 38 }} />
      </View>

      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.brandCard}>
          <Image
            source={require("../assets/images/sfj-logo.png")}
            style={styles.logo}
            contentFit="contain"
          />
          <Text style={styles.brandName}>{KITCHEN_NAME}</Text>
          <Text style={styles.brandTag}>Good Food, Happy Mood</Text>
        </View>

        <Text style={styles.section}>Printer</Text>

        <View style={styles.printerRow}>
          <View style={styles.iconCircle}>
            <Ionicons name="print" size={18} color={theme.color.onBrandPrimary} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.printerName} testID="settings-printer-name">
              {printer ? printer.name : "No printer connected"}
            </Text>
            <Text style={styles.printerSub}>
              {isNativePrinterAvailable() ? "58mm Bluetooth ESC/POS" : "Demo mode (Expo Go preview)"}
            </Text>
          </View>
          <Pressable
            testID="settings-change-printer"
            onPress={onChangePrinter}
            style={styles.smallBtn}
          >
            <Text style={styles.smallBtnText}>{printer ? "Change" : "Connect"}</Text>
          </Pressable>
        </View>

        {printer ? (
          <Pressable
            testID="settings-disconnect"
            onPress={onDisconnect}
            style={({ pressed }) => [styles.dangerBtn, pressed && { opacity: 0.85 }]}
          >
            <Ionicons name="unlink-outline" size={16} color={theme.color.error} />
            <Text style={styles.dangerText}>Disconnect printer</Text>
          </Pressable>
        ) : null}

        <Text style={[styles.section, { marginTop: theme.spacing.xxl }]}>About</Text>
        <View style={styles.aboutCard}>
          <Text style={styles.aboutText}>
            Sticky-note quotes are generated by the Shree Food Junction quote service. Print to a
            58mm Bluetooth thermal printer to delight every customer.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.color.surface },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  iconBtn: { padding: theme.spacing.sm },
  headerTitle: {
    fontFamily: theme.font.display,
    fontSize: theme.scale.xl,
    color: theme.color.onSurface,
    fontWeight: "700",
  },
  scroll: { padding: theme.spacing.xl, paddingBottom: theme.spacing.xxxl },
  brandCard: {
    alignItems: "center",
    paddingVertical: theme.spacing.xl,
    backgroundColor: theme.color.surfaceSecondary,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.color.border,
    marginBottom: theme.spacing.xxl,
  },
  logo: { width: 96, height: 96, borderRadius: 16, marginBottom: theme.spacing.md },
  brandName: {
    color: theme.color.onSurface,
    fontFamily: theme.font.display,
    fontSize: theme.scale["2xl"],
    fontWeight: "800",
  },
  brandTag: {
    color: theme.color.muted,
    fontFamily: theme.font.text,
    fontSize: theme.scale.sm,
    marginTop: 4,
  },
  section: {
    fontFamily: theme.font.text,
    color: theme.color.brandSecondary,
    fontWeight: "800",
    fontSize: theme.scale.sm,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: theme.spacing.md,
  },
  printerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    backgroundColor: theme.color.surfaceSecondary,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.color.border,
    padding: theme.spacing.lg,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.color.brandPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  printerName: {
    color: theme.color.onSurface,
    fontFamily: theme.font.text,
    fontWeight: "700",
    fontSize: theme.scale.lg,
  },
  printerSub: {
    color: theme.color.muted,
    fontFamily: theme.font.text,
    fontSize: theme.scale.sm,
    marginTop: 2,
  },
  smallBtn: {
    backgroundColor: theme.color.brandPrimary,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 8,
    borderRadius: theme.radius.pill,
  },
  smallBtnText: {
    color: theme.color.onBrandPrimary,
    fontFamily: theme.font.text,
    fontWeight: "800",
    fontSize: theme.scale.sm,
  },
  dangerBtn: {
    marginTop: theme.spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.sm,
    paddingVertical: 12,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.color.error,
    backgroundColor: "rgba(198,93,71,0.06)",
  },
  dangerText: {
    color: theme.color.error,
    fontFamily: theme.font.text,
    fontWeight: "800",
    fontSize: theme.scale.base,
  },
  aboutCard: {
    backgroundColor: theme.color.surfaceSecondary,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.color.border,
    padding: theme.spacing.lg,
  },
  aboutText: {
    color: theme.color.onSurfaceSecondary,
    fontFamily: theme.font.text,
    fontSize: theme.scale.base,
    lineHeight: 22,
  },
});
