// Design tokens from /app/design_guidelines.json
export const theme = {
  color: {
    surface: "#FDFBF7",
    onSurface: "#2D2A26",
    surfaceSecondary: "#F4EFE6",
    onSurfaceSecondary: "#3D3A36",
    surfaceTertiary: "#EAE4D9",
    onSurfaceTertiary: "#4D4A46",
    surfaceInverse: "#2D2A26",
    onSurfaceInverse: "#FDFBF7",
    brand: "#E8B831",
    brandPrimary: "#E8B831",
    onBrandPrimary: "#2D2A26",
    brandSecondary: "#D9734E",
    onBrandSecondary: "#FDFBF7",
    brandTertiary: "#F7E5A9",
    onBrandTertiary: "#2D2A26",
    success: "#658A64",
    onSuccess: "#FDFBF7",
    warning: "#E8B831",
    error: "#C65D47",
    onError: "#FDFBF7",
    info: "#8C857B",
    border: "#E0D8C8",
    borderStrong: "#C2B8A3",
    divider: "#EAE4D9",
    muted: "#8C857B",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 20,
    pill: 999,
  },
  font: {
    display: "Fraunces",
    text: "Nunito",
    hand: "Caveat",
  },
  scale: {
    sm: 12,
    base: 14,
    lg: 16,
    xl: 20,
    "2xl": 24,
    "3xl": 32,
    "4xl": 40,
  },
} as const;

export type Theme = typeof theme;
